# Generated by Django 3.1.7 on 2021-04-16 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_auto_20210416_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_cap',
            name='company_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboards.company'),
        ),
    ]
