# Generated by Django 3.1.7 on 2021-04-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_market_cap_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stock_price',
            field=models.IntegerField(verbose_name='Precio por acción'),
        ),
        migrations.AlterField(
            model_name='company',
            name='stock_volume',
            field=models.IntegerField(verbose_name='Acciones en circulación'),
        ),
    ]
