# Generated by Django 3.1.7 on 2021-04-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_auto_20210416_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market_cap',
            old_name='company_id',
            new_name='company',
        ),
    ]
