# Generated by Django 3.1.7 on 2021-04-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_auto_20210416_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market_cap',
            name='market_cap_id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
    ]
