# Generated by Django 3.1.7 on 2021-04-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_auto_20210416_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='market_value',
            field=models.CharField(default=1000, max_length=500000, verbose_name='[6524, 9896, 4155, 1948, 6300, 6172, 8545, 681, 9982, 6010, 1678, 4286, 7490, 5320, 5988, 5581, 9018, 4810, 2837, 9565, 6788, 4817, 5778, 7632, 4649, 8919, 4977, 6635, 2698, 7119, 8611, 2685, 5717, 1834, 929, 4101, 7684, 2410, 2315, 2282, 1913, 8680, 3153, 9744, 7362, 7440, 9588, 4423, 9808, 5872]'),
        ),
    ]
