# Generated by Django 3.1.7 on 2021-04-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_auto_20210418_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='[334, 869, 4256, 5280, 9523, 8243, 6932, 6886, 3633, 4183, 7745, 2283, 8317, 129, 8725, 809, 7239, 819, 7081, 8914, 7725, 983, 2139, 6551, 8797, 6642, 3027, 9368, 3039, 3376, 9576, 1026, 1586, 4460, 7128, 4458, 471, 5435, 1311, 2219, 1239, 7259, 9755, 2289, 2810, 1066, 4500, 7620, 8312, 4745]',
        ),
        migrations.AddField(
            model_name='company',
            name='market_value',
            field=models.CharField(default='[4343, 1985, 4852, 7583, 3532, 5614, 4763, 3480, 4394, 8685, 8827, 6785, 3356, 6892, 9877, 4456, 2296, 1460, 2086, 6178, 8715, 5452, 9118, 8220, 1722, 4750, 4790, 3234, 1808, 189, 4302, 6949, 7742, 1852, 2553, 1912, 6515, 8988, 5600, 1754, 9943, 7919, 9911, 6159, 4272, 1012, 8003, 7452, 281, 5058]', max_length=500000, verbose_name='Valores a mercado'),
        ),
    ]
